import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/exercise_model.dart';

class ExerciseManager extends ChangeNotifier {
  // Instantiates foundational pipeline channels linking application state to Firebase services
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // --- 1. CORE SYSTEM ASSETS ---
  // Default static template movements packaged locally and made available to every user profile
  final List<Exercise> _premadeExercises = [
    Exercise(id: 'pre_1', name: 'Bench Press', reps: 10, weight: 60.0),
    Exercise(id: 'pre_2', name: 'Squats', reps: 8, weight: 80.0),
    Exercise(id: 'pre_3', name: 'Deadlift', reps: 5, weight: 100.0),
    Exercise(id: 'pre_4', name: 'Lat Pulldown', reps: 12, weight: 45.0),
    Exercise(id: 'pre_5', name: 'Shoulder Press', reps: 10, weight: 30.0),
    Exercise(id: 'pre_6', name: 'Bicep Curls', reps: 12, weight: 15.0),
  ];

  // --- 2. PERSONALIZED PROFILE LOGS ---
  // RAM cache list hosting custom workout movements generated by the active user profile
  List<Exercise> _customExercises = [];

  // Public getter compiling static systemic options alongside tailored cloud datasets for UI use
  List<Exercise> get exercises => [..._premadeExercises, ..._customExercises];

  // --- DATABASE UTILITIES (CRUD) ---

  // READ: Pulls all unique custom exercise documents mapped under the active user's identification path
  Future<void> loadExercises() async {
    final user = _auth.currentUser;
    if (user == null) {
      _clearLocalData(); // Force instant memory cache wipe if authentication checks return invalid parameters
      return;
    }

    try {
      // ACCOUNT ISOLATION FIX: Empties out RAM tracking cache arrays immediately 
      // to guarantee data metrics are completely wiped across user transitions
      _customExercises = [];

      final snapshot = await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('custom_exercises')
          .get();

      // De-serialize raw JSON data keys directly into native code models maps structures
      _customExercises = snapshot.docs.map((doc) {
        final data = doc.data();
        return Exercise(
          id: doc.id,
          name: data['name'] ?? '',
          reps: (data['reps'] as num?)?.toInt() ?? 0,
          weight: (data['weight'] as num?)?.toDouble() ?? 0.0,
        );
      }).toList();

      notifyListeners(); // Alert consumer layout modules to re-render screen view list items
    } catch (e) {
      debugPrint("Error loading exercises: $e");
    }
  }

  // CREATE: Appends a completely brand-new movement model entry payload into Cloud collections
  Future<void> addExercise(String name, int reps, double weight) async {
    final user = _auth.currentUser;
    if (user == null) return;

    final String exerciseId = DateTime.now().millisecondsSinceEpoch.toString(); // Compile unique identification code string

    try {
      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('custom_exercises')
          .doc(exerciseId)
          .set({
        'name': name,
        'reps': reps,
        'weight': weight,
        'date': DateTime.now(),
      });

      // Synchronize changes to local runtime RAM variables lists to maintain prompt responsiveness
      _customExercises.add(Exercise(
        id: exerciseId,
        name: name,
        reps: reps,
        weight: weight,
      ));

      notifyListeners();
    } catch (e) {
      debugPrint("Error saving exercise: $e");
    }
  }

  // UPDATE: Modifies targeted variables fields inside designated user storage paths maps
  Future<void> updateExercise(String id, String name, int reps, double weight) async {
    // SECURITY GUARD: Abort operations if the target ID matches predefined system asset parameters
    final user = _auth.currentUser;
    if (user == null || id.startsWith('pre_')) return; 

    try {
      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('custom_exercises')
          .doc(id)
          .update({
        'name': name,
        'reps': reps,
        'weight': weight,
      });

      // Sync data changes directly inside local item positions offsets rows
      int index = _customExercises.indexWhere((ex) => ex.id == id);
      if (index != -1) {
        _customExercises[index] = Exercise(id: id, name: name, reps: reps, weight: weight);
        notifyListeners();
      }
    } catch (e) {
      debugPrint("Error updating exercise: $e");
    }
  }

  // DELETE: Strips a targeted movement item completely out of cloud mapping paths registers
  Future<void> deleteExercise(String id) async {
    // PROTECTION GUARD: Prevent erasure requests if targeting system preset items
    final user = _auth.currentUser;
    if (user == null || id.startsWith('pre_')) return;

    try {
      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('custom_exercises')
          .doc(id)
          .delete();

      _customExercises.removeWhere((ex) => ex.id == id); // Evict from ongoing local list scopes tracking
      notifyListeners();
    } catch (e) {
      debugPrint("Error deleting exercise: $e");
    }
  }

  // System cleaning script executed automatically during profile logout routines
  void _clearLocalData() {
    _customExercises = [];
    notifyListeners();
  }
}