// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbqhcWcomUQ2De4qZLT-iFZ81hy_SjNJY',
    appId: '1:458869922508:web:9d20831aa1563925b50069',
    messagingSenderId: '458869922508',
    projectId: 'fitness-app-932fb',
    authDomain: 'fitness-app-932fb.firebaseapp.com',
    storageBucket: 'fitness-app-932fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5myRJEf_plZUQXd_twWMlrGDDxwLhAts',
    appId: '1:458869922508:android:655a8476fab13069b50069',
    messagingSenderId: '458869922508',
    projectId: 'fitness-app-932fb',
    storageBucket: 'fitness-app-932fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3-Agxae3T_kiLdfepEjdR3zNZmPLmqZ4',
    appId: '1:458869922508:ios:ffe8519f73cb70d0b50069',
    messagingSenderId: '458869922508',
    projectId: 'fitness-app-932fb',
    storageBucket: 'fitness-app-932fb.firebasestorage.app',
    iosBundleId: 'com.example.fitnessFlutterPn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3-Agxae3T_kiLdfepEjdR3zNZmPLmqZ4',
    appId: '1:458869922508:ios:ffe8519f73cb70d0b50069',
    messagingSenderId: '458869922508',
    projectId: 'fitness-app-932fb',
    storageBucket: 'fitness-app-932fb.firebasestorage.app',
    iosBundleId: 'com.example.fitnessFlutterPn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbqhcWcomUQ2De4qZLT-iFZ81hy_SjNJY',
    appId: '1:458869922508:web:0c146e0042a9b198b50069',
    messagingSenderId: '458869922508',
    projectId: 'fitness-app-932fb',
    authDomain: 'fitness-app-932fb.firebaseapp.com',
    storageBucket: 'fitness-app-932fb.firebasestorage.app',
  );
}
